[cmake]
version = "3.15"
cmkr-include = "cmake/cmkr.cmake"

[project]
name = "TraceUtilities"
include-before = [
	"cmake/msvc-static-runtime.cmake",
	"cmake/msvc-configurations.cmake",
]

[fetch-content.x64dbg]
url = "https://sourceforge.net/projects/x64dbg/files/snapshots/snapshot_2023-06-10_18-05.zip"
sha1 = "04468bd61fb36d6b10d17f342f03ef12f5b2ce62"
include-after = ["cmake/x64dbg.cmake"]

[template.plugin]
type = "shared"
add-function = "x64dbg_plugin"

[target.TraceUtilities]
type = "plugin"
sources = [
    "src/*.cpp",
    "src/*.h",
    "src/*.rc",
]

[target.TraceUtilities.properties]
CXX_STANDARD = "17"
CXX_STANDARD_REQUIRED = true
